### PR TITLE
Fix datetime parsing for postgresql

### PR DESCRIPTION
**Pull request by nikita-d**

### CODE REVIEW

**Comment by nigelm** [comment]
Thanks for this - unfortunately as I am away on a course right now, and going immediately into an insanely busy couple of weeks I'll not be able to look further until the second half of December.

Would it be possible to rework to not include the import of local into the repo?  If not I can pick from the change sets.

Thanks
   Nigel.

**Comment by nikita-d** [comment]
Local dir should have gone, I'll look into it.

**Comment by ccakes** [comment]
This is pretty old but Postgres support is something I'm interested in as well to stop me rolling my own version.

From a quick look at the changes, the cpanfile + snapshot should be removed as they're not present in the original dist. Also the dependency on boolean isn't actually required, that looks like an issue in the Time::Moment documentation. This example works fine:

```perl
perl -MTime::Moment \
  -e 'print Time::Moment->from_string("2017-03-27 04:53:03.452374z", lenient => 1)'
```

@nigelm with these changes would you merge a PR or is this something you're not using/maintaining these days?

**Comment by nigelm** [comment]
Oh wow - my apologies, this obviously slipped my mind, and then I didn't have a reminder sitting there for this...

**Comment by nigelm** [comment]
OK, rather than take this particular pull request with its specific detection of PostgreSQL, I have reworked the code to both use a looser parser, and drop a Z timezone marker in if there is no timezone support in the timestamp.

Please try this and see if it works for you.

**Comment by ccakes** [comment]
Awesome, thanks!

**Pull request closed without merging**
